[[plugins]]
repo = 'arzg/vim-colors-xcode'
# hook_add = '''
#   colorscheme xcodedark
# '''

[[plugins]]
repo = 'cormacrelf/vim-colors-github'
# hook_add = '''
#   let g:github_colors_soft = 1
#   colorscheme github
# '''

[[plugins]]
repo = 'yasukotelin/shirotelin'
# hook_add = '''
#   colorscheme shirotelin
# '''


[[plugins]]
repo = 'morhetz/gruvbox'
# hook_add = '''
#   set background=light
#   colorscheme gruvbox
# '''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  " set background=light
  colorscheme iceberg
'''

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
  let g:tokyonight_style = 'day' " available: night, storm, day
  let g:tokyonight_sidebars = [ "qf", "vista_kind", "terminal", "packer" ]
  colorscheme tokyonight
'''

[[plugins]]
repo = 'dracula/vim'
# hook_add = '''
#   colorscheme dracula
# '''

[[plugins]]
repo = 'lifepillar/vim-solarized8'
# hook_add = '''
#   set background=light
#   colorscheme solarized8
# '''

[[plugins]]
repo = 'kjssad/quantum.vim'
# hook_add = '''
#   colorscheme quantum
#   set background=dark
# '''
# hook_post_source = '''
#   let g:quantum_black=1
#   let g:quantum_italics=1
#   highlight link Identifier Keyword
#   highlight Comment gui=none
# '''

[[plugins]]
repo = 'sainnhe/edge'
# hook_add = '''
#   set background=dark
#   colorscheme edge
# '''

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
# hook_add = '''
#   set background=dark
#   colorscheme nightfly
# '''

[[plugins]]
repo = 'kyazdani42/blue-moon'
# hook_add = '''
#   set background=dark
#   colorscheme blue-moon
# '''

[[plugins]]
repo = 'jim-at-jibba/ariake-vim-colors'

[[plugins]]
repo = 'Th3Whit3Wolf/space-nvim'
