[[plugins]]
repo = 'yasukotelin/shirotelin'
# hook_add = '''
#   colorscheme shirotelin
# '''

[[plugins]]
repo = 'morhetz/gruvbox'
# hook_add = '''
#   set background=light
#   colorscheme gruvbox
# '''

[[plugins]]
repo = 'cocopon/iceberg.vim'
# hook_add = '''
#   set background=light
#   colorscheme iceberg
# '''

[[plugins]]
repo = 'folke/tokyonight.nvim'
# hook_add = '''
#   let g:tokyonight_style = 'night' " available: night, storm, day
#   let g:tokyonight_sidebars = [ "qf", "vista", "vista_kind", "terminal", "fern" ]
#   set background=dark
#   colorscheme tokyonight
# '''

[[plugins]]
repo = 'dracula/vim'
# hook_add = '''
#   colorscheme dracula
# '''

[[plugins]]
repo = 'sainnhe/edge'
# hook_add = '''
#   set background=dark
#   colorscheme edge
# '''

[[plugins]]
repo = 'rose-pine/neovim'
hook_add = '''
lua << EOF
vim.g.rose_pine_variant = 'moon' -- main or moon or dawn
vim.cmd('colorscheme rose-pine')
EOF
'''

