[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'lambdalisue/guise.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = ['denops.vim']
hook_add = '''
  noremap <silent><C-s><C-s> <cmd>GinStatus<CR>
  au FileType gin-status noremap <buffer> <C-c><C-c> <cmd>Gin commit<CR>
'''

[[plugins]]
repo = 'pyonk/dexercism.vim'
depends = ['denops.vim']
