[[plugins]]
of_ft=['markdown']
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
hook_source = '''
let g:preview_markdown_parser='glow'
let g:preview_markdown_auto_update=1
'''
