[[plugins]]
on_ft=['markdown']
repo = 'plasticboy/vim-markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_conceal = 0
  let g:vim_markdown_conceal_code_blocks = 0
'''

[[plugins]]
of_ft=['markdown']
repo = 'godlygeek/tabular'

[[plugins]]
on_ft=['markdown']
repo = 'previm/previm'
hook_add = '''
  let g:previm_open_cmd = 'open -a "Google Chrome"'
	let g:previm_plantuml_imageprefix = 'http://localhost:8080/png/'
'''
