[[plugins]]
on_ft = 'python'
repo = 'tweekmonster/django-plus.vim'

[[plugins]]
on_ft = 'python'
repo = 'vim-python/python-syntax'
hook_add = '''
  let g:python_highlight_all = 1
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'psf/black'
on_ft = 'python'
hook_add = '''
  autocmd BufWritePre *.py execute ':Black'
'''

