import = ["/Users/pyonk/.config/alacritty/colors/tokyonight-moon.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = 18.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 1
y = 7

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "none"
